version: "3"
services:
  todotests:
    image: todotests
    environment:
      - FRONT_HOST=todofront
    restart: on-failure
    depends_on:
      - todoback
      - todofront
      
  todofront:
    image: todofrontend
    environment:
      - REACT_APP_API_HOST=todoback
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - todoback

  todoback:
    image: todobackend
    ports:
      - 3001:3001
    restart: on-failure